CREATE TABLE UTENTI(
    OID INTEGER,
    EXTERNAL_ID VARCHAR2(60) NOT NULL
);

CREATE INDEX PK_UTENTI ON UTENTI(OID);
CREATE INDEX PKP_UTENTI ON UTENTI(EXTERNAL_ID);

ALTER TABLE UTENTI ADD (
    CONSTRAINT PK_UTENTI
    PRIMARY KEY (OID),
    
    CONSTRAINT U_UTENTI
    UNIQUE (EXTERNAL_ID)
);

CREATE SEQUENCE SEQ_UTENTI
    INCREMENT BY 1
    START WITH 1
    MAXVALUE 9999999
    MINVALUE 1
    NOCYCLE
;

CREATE TRIGGER TR_UTENTI
BEFORE INSERT ON UTENTI
FOR EACH ROW 
BEGIN
    :NEW.OID := SEQ_UTENTI.NEXTVAL;
END;
/