// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TriviaRepository.Context.TriviaModel;

[Table("CATEGORIE")]
[Index("IdCategoria", Name = "PKP_CATEGORIE")]
public partial class Categorie
{
    [Key]
    [Column("OID", TypeName = "NUMBER(38)")]
    public decimal Oid { get; set; }

    [Required]
    [Column("ID_CATEGORIA")]
    [StringLength(5)]
    [Unicode(false)]
    public string IdCategoria { get; set; }

    [Column("DS_CATEGORIA")]
    [StringLength(30)]
    [Unicode(false)]
    public string DsCategoria { get; set; }

    [Required]
    [Column("FL_ATTIVA")]
    [StringLength(1)]
    [Unicode(false)]
    public string FlAttiva { get; set; }

    [InverseProperty("OidCategoriaNavigation")]
    public virtual ICollection<Domande> Domande { get; set; } = new List<Domande>();
}