// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DatabaseContext.Context.TriviaModel;

[Table("DOMANDE_RISPOSTE")]
[Index("OidDomanda", "IdRisposta", Name = "PKP_DOMANDE_RISPOSTE")]
public partial class DomandeRisposte
{
    [Key]
    [Column("OID", TypeName = "NUMBER(38)")]
    public decimal Oid { get; set; }

    [Column("OID_DOMANDA", TypeName = "NUMBER(38)")]
    public decimal OidDomanda { get; set; }

    [Column("ID_RISPOSTA")]
    [Precision(4)]
    public int? IdRisposta { get; set; }

    [Column("DS_RISPOSTA")]
    [StringLength(255)]
    [Unicode(false)]
    public string DsRisposta { get; set; }

    [Required]
    [Column("FL_CORRETTA")]
    [StringLength(1)]
    [Unicode(false)]
    public string FlCorretta { get; set; }

    [ForeignKey("OidDomanda")]
    [InverseProperty("DomandeRisposte")]
    public virtual Domande OidDomandaNavigation { get; set; }

    [InverseProperty("OidRispostaNavigation")]
    public virtual ICollection<PartiteUtentiRisposte> PartiteUtentiRisposte { get; set; } = new List<PartiteUtentiRisposte>();
}