// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TriviaRepository.Context.TriviaModel;

[Table("PARTITE_DOMANDE")]
[Index("OidPartita", "OidDomanda", Name = "PKP_PARTITE_DOMANDE")]
public partial class PartiteDomande
{
    [Key]
    [Column("OID", TypeName = "NUMBER(38)")]
    public decimal Oid { get; set; }

    [Column("OID_PARTITA", TypeName = "NUMBER(38)")]
    public decimal OidPartita { get; set; }

    [Column("OID_DOMANDA", TypeName = "NUMBER(38)")]
    public decimal OidDomanda { get; set; }

    [Required]
    [Column("FL_PROPOSTA")]
    [StringLength(1)]
    [Unicode(false)]
    public string FlProposta { get; set; }

    [Column("NM_DOMANDA")]
    [Precision(3)]
    public int NmDomanda { get; set; }

    [ForeignKey("OidDomanda")]
    [InverseProperty("PartiteDomande")]
    public virtual Domande OidDomandaNavigation { get; set; }

    [ForeignKey("OidPartita")]
    [InverseProperty("PartiteDomande")]
    public virtual Partite OidPartitaNavigation { get; set; }
}