// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TriviaRepository.Context.TriviaModel;

[Table("PARTITE_UTENTI_RISPOSTE")]
[Index("OidPartitaUtente", "OidDomanda", "OidRisposta", Name = "PKP_PARTITE_UTENTI_RISPOSTE")]
public partial class PartiteUtentiRisposte
{
    [Key]
    [Column("OID", TypeName = "NUMBER(38)")]
    public decimal Oid { get; set; }

    [Column("OID_PARTITA_UTENTE", TypeName = "NUMBER(38)")]
    public decimal OidPartitaUtente { get; set; }

    [Column("OID_DOMANDA", TypeName = "NUMBER(38)")]
    public decimal OidDomanda { get; set; }

    [Column("OID_RISPOSTA", TypeName = "NUMBER(38)")]
    public decimal OidRisposta { get; set; }

    [Column("FL_CORRETTA")]
    [StringLength(1)]
    [Unicode(false)]
    public string FlCorretta { get; set; }

    [ForeignKey("OidDomanda")]
    [InverseProperty("PartiteUtentiRisposte")]
    public virtual Domande OidDomandaNavigation { get; set; }

    [ForeignKey("OidPartitaUtente")]
    [InverseProperty("PartiteUtentiRisposte")]
    public virtual PartiteUtenti OidPartitaUtenteNavigation { get; set; }

    [ForeignKey("OidRisposta")]
    [InverseProperty("PartiteUtentiRisposte")]
    public virtual DomandeRisposte OidRispostaNavigation { get; set; }
}