// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DatabaseContext.Context.TriviaModel;

[Table("STORICO_PARTITE_UTENTI_DOM")]
[Index("OidStoricoPartitaUtente", Name = "PKP_STORICO_PARTITE_UTENTI_DOM")]
public partial class StoricoPartiteUtentiDom
{
    [Key]
    [Column("OID", TypeName = "NUMBER(38)")]
    public decimal Oid { get; set; }

    [Column("OID_STORICO_PARTITA_UTENTE", TypeName = "NUMBER(38)")]
    public decimal OidStoricoPartitaUtente { get; set; }

    [Column("DS_CATEGORIA")]
    [StringLength(30)]
    [Unicode(false)]
    public string DsCategoria { get; set; }

    [Column("FL_CORRETTA")]
    [StringLength(1)]
    [Unicode(false)]
    public string FlCorretta { get; set; }

    [ForeignKey("OidStoricoPartitaUtente")]
    [InverseProperty("StoricoPartiteUtentiDom")]
    public virtual StoricoPartiteUtenti OidStoricoPartitaUtenteNavigation { get; set; }
}